[package]
name = "example-01"
version = "0.1.0"
authors = ["Matt Hayes <matt@mysterycommand.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "0.1.7"
wasm-bindgen = "0.2.43"
web-sys = { version = "0.3.20", features = [ "console" ] }
